// popup.js - Handles the UI display, network dispatch, and queue flushing
function logStatus(msg) {
  const el = document.getElementById('status-log');
  el.style.display = 'block';
  el.innerHTML += `<div>> ${msg}</div>`;
}

document.getElementById('generate-btn').addEventListener('click', async () => {
  const reportEl = document.getElementById('report');
  const vaultEl = document.getElementById('vault');
  const btn = document.getElementById('generate-btn');

  // UI Setup: Lock the button and reset state elements
  btn.disabled = true;
  btn.innerText = "Processing...";
  document.getElementById('status-log').innerHTML = '';
  reportEl.innerHTML = '<span class="loader">Initializing engine...</span>';

  try {
    logStatus("Reading staging metrics from accumulation queue...");
    
    // 1. Fetch BOTH the fresh data queue and the historical indices mapping
    const storage = await chrome.storage.local.get(['accumulationQueue', 'historicalState']);
    const queue = storage.accumulationQueue || [];
    const stateData = storage.historicalState || {};

    // Safety Guard: Abort early if no new updates have been caught
    if (queue.length === 0) {
      logStatus("No new activity caught in the queue.");
      reportEl.innerHTML = "<b>Your feed queue is currently empty.</b> Browse Instagram for a moment to harvest new updates.";
      btn.disabled = false;
      btn.innerText = "Compile Morning Digest";
      return;
    }

    logStatus(`Shipping ${queue.length} uncompiled changes to AI layer...`);
    reportEl.innerHTML = '<span class="loader">Gemini multimodal parsing engines processing data...</span>';

    // 2. Fire the staged storage queue directly down to our local proxy server
    const response = await fetch('http://localhost:3000/api/digest', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ events: queue }) 
    });

    if (!response.ok) {
      throw new Error(`Proxy Node rejected transfer code: ${response.status}`);
    }

    const serverData = await response.json();
    logStatus("Processing complete. Formatting outputs.");

    // 3. Render the summary report narrative generated by Gemini
    reportEl.innerHTML = serverData.digest;

    // 4. Render active stories into the Anonymous Media Vault using historicalState refs
    vaultEl.innerHTML = ''; // wipe the initial loading text
    let mediaCount = 0;

    for (const id in stateData) {
      if (stateData[id].type === 'STORY' && stateData[id].localCdn) {
        mediaCount++;
        const cdn = stateData[id].localCdn;
        
        // Dynamically differentiate video nodes from static image nodes
        if (cdn.includes('.mp4') || cdn.includes('video')) {
          const video = document.createElement('video');
          video.src = cdn;
          video.controls = true;
          video.muted = true;
          vaultEl.appendChild(video);
        } else {
          const img = document.createElement('img');
          img.src = cdn;
          vaultEl.appendChild(img);
        }
      }
    }

    if (mediaCount === 0) {
      vaultEl.innerHTML = '<span class="loader" style="font-size:11px;">No unread stories inside storage buffer.</span>';
    } else {
      logStatus(`Injected ${mediaCount} elements into Anonymous Media Vault.`);
    }

    // 5. THE FIX: Wipe out the queue tracking storage block so we don't double-process these items next time
    await chrome.storage.local.remove('accumulationQueue');
    logStatus("Digest compiled successfully. Queue cleared.");

  } catch (err) {
    logStatus(`<span style="color:red">FAULT: ${err.message}</span>`);
    reportEl.innerHTML = "<b>Pipeline Breakpoint.</b> Verify that your local node endpoint is online (`node server.js`).";
  } finally {
    btn.disabled = false;
    btn.innerText = "Recompile Morning Digest";
  }
});